<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-CVVOB1KD" failures="2" tests="6" name="Test" time="9.125" errors="0" timestamp="2020-05-17T01:02:29 IST">
  <testcase classname="com.APIFramework.BDDTestCases.GetRequest" name="getRequest" time="3.856"/>
  <testcase classname="com.APIFramework.APITestCases.HTTPMethod_GET" name="getEmployeeData" time="0.684"/>
  <testcase classname="com.APIFramework.APITestCases.HTTPMethod_DELETE" name="deleteEmployeeData" time="1.058">
    <failure type="java.lang.AssertionError" message="expected [success] but found [failed]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [failed]
at com.APIFramework.APITestCases.HTTPMethod_DELETE.deleteEmployeeData(HTTPMethod_DELETE.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteEmployeeData -->
  <testcase classname="com.APIFramework.APITestCases.HTTPMethod_GET_IDData" name="getEmployeeDataByID" time="1.002">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at com.APIFramework.Assertions.ResponseAssertions.responseStatusCodeValidation(ResponseAssertions.java:16)
at com.APIFramework.APITestCases.HTTPMethod_GET_IDData.getEmployeeDataByID(HTTPMethod_GET_IDData.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getEmployeeDataByID -->
  <testcase classname="com.APIFramework.APITestCases.HTTPMethod_POST" name="postEmployeeData" time="1.054"/>
  <testcase classname="com.APIFramework.APITestCases.HTTPMethod_PUT" name="putEmployeeData" time="1.103"/>
</testsuite> <!-- Test -->
